### ISSUE TITLE
Navigatie menu

### ISSUE THREAD

**Issue by ExCellRaD** [HeinPauwelyn/WatchFriends#26]
- home
- eigen profiel
- lijsten: watched watching watchlist (menuoptie per lijst)
- upgrade naar premium
- settings
- uitloggen

**Comment by mickverm** [comment]
![sidebar nav](https://cloud.githubusercontent.com/assets/1834265/19417034/04a86b56-93a2-11e6-99a6-d88287339e1a.png)
