### ISSUE TITLE
Technische analyse

### ISSUE THREAD

**Issue by HeinPauwelyn** [HeinPauwelyn/WatchFriends#39]
Technische analyse beschrijven voor alles wat we gaan doen in de applicatie + gaat ook de link naar GitHub bevatten.

**Comment by HeinPauwelyn** [comment]
Is geüpload op de Drive. Stond eigenlijk niet in de opgave dat dit moest gebeuren voor de 3<sup>de</sup> deelopdracht maar so what. Tis nu gemaakt en voeg dit dus maar toe aan het document.

**Comment by ExCellRaD** [comment]
Een paar opmerkingen:

API moeten we nog onderzoeken welke we gaan gebruiken, TVDB staat nog niet vast

> Zowel de Android als de website kunnen real-time communiceren met de server om direct gegevens over de progressie van de achievements en de watchlist aan te vullen.

Die zijn niet real-time, de zoekfunctie wel.
> Daarnaast maken we ook gebruik van het internet om verschillende problemen op te zoeken.
> De volledige applicatie wordt geschreven met Android Studio, Webstorm en Visual Studio.

Moet niet vemeld worden, ik gebruik geen webstorm dus klopt ook niet.

**Comment by HeinPauwelyn** [comment]
Punten die ik ga verbeteren en welke niet

1. Denk wel dat er ergens real-time communicatie moet zijn tussen website en server. Over android app kunnen we discuteren en eventueel later weg laten vallen.
2. Ik gebruik webstorm wel voor frontend javascript, css en html. &rarr; is misschien ook beter dat ik dit niet vermeld.
3. Internet gebruiken mag inderdaad weg.
4. Ga TVDB niet vermelden

**PS:** is ook een voorlopige analyse hé we kunnen nog altijd veranderen.
